#!/bin/bash
set -e

if [ -z $1 ]; then
  grep proxy_pass /etc/nginx/conf.d/stevedesmond.ca.conf
  exit
fi

sudo sed -i 's/proxy\_pass.*/proxy_pass http:\/\/127.0.0.1:'"$1"'\/;/' /etc/nginx/conf.d/stevedesmond.ca.conf
sudo service nginx configtest
sudo service nginx restart
